# Generated by Django 5.0 on 2025-08-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='主分类名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='URL别名')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越大，排序越靠后', verbose_name='排序权重')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('icon', models.CharField(blank=True, help_text='例如：fas fa-book', max_length=50, null=True, verbose_name='图标类名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '主分类',
                'verbose_name_plural': '主分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='URL别名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='子分类名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='URL别名')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标类名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Pythonfun.maincategory', verbose_name='所属主分类')),
            ],
            options={
                'verbose_name': '子分类',
                'verbose_name_plural': '子分类',
                'ordering': ['id'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('content_type', models.CharField(choices=[('TU', '教程'), ('ST', '结构'), ('SO', '故事')], default='TU', max_length=2, verbose_name='内容类型')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, verbose_name='预计阅读时间')),
                ('content_html', models.TextField(help_text='用于存储TinyMCE编辑器的HTML内容', verbose_name='富文本内容')),
                ('content_code', models.TextField(blank=True, help_text='用于存储Monaco编辑器的代码', null=True, verbose_name='代码内容')),
                ('code_language', models.CharField(default='python', max_length=50, verbose_name='代码语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pythonfun.subcategory', verbose_name='所属分类')),
                ('tags', models.ManyToManyField(blank=True, to='Pythonfun.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
