# Generated by Django 5.2.3 on 2025-08-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pythonfun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
