# Generated by Django 5.0 on 2025-08-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pythonfun', '0002_article_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_id', models.AutoField(primary_key=True, serialize=False, verbose_name='库ID')),
                ('library_name', models.CharField(max_length=100, unique=True, verbose_name='库名称')),
                ('library_name_cn', models.CharField(max_length=100, verbose_name='库中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('is_standard', models.BooleanField(default=False, verbose_name='是否标准库')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库信息',
                'verbose_name_plural': '库信息',
                'db_table': 'library_info',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('operation_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='操作类型ID')),
                ('operation_name', models.CharField(max_length=100, unique=True, verbose_name='操作类型名称')),
                ('operation_name_cn', models.CharField(max_length=100, verbose_name='操作类型中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '操作类型',
                'verbose_name_plural': '操作类型',
                'db_table': 'operation_type',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False, verbose_name='模块ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Pythonfun.library', verbose_name='所属库')),
            ],
            options={
                'verbose_name': '模块信息',
                'verbose_name_plural': '模块信息',
                'db_table': 'module_info',
                'unique_together': {('library', 'module_name')},
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False, verbose_name='函数ID')),
                ('function_name', models.CharField(max_length=200, verbose_name='函数名称')),
                ('function_name_cn', models.CharField(blank=True, max_length=200, null=True, verbose_name='函数中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('description_cn', models.TextField(blank=True, null=True, verbose_name='中文描述')),
                ('syntax', models.TextField(blank=True, null=True, verbose_name='语法')),
                ('parameters_text', models.TextField(blank=True, null=True, verbose_name='参数')),
                ('return_value', models.TextField(blank=True, null=True, verbose_name='返回值')),
                ('return_value_cn', models.TextField(blank=True, null=True, verbose_name='返回值中文')),
                ('example', models.TextField(blank=True, null=True, verbose_name='示例')),
                ('example_cn', models.TextField(blank=True, null=True, verbose_name='中文示例')),
                ('availability', models.CharField(blank=True, max_length=100, null=True, verbose_name='可用性')),
                ('version_added', models.CharField(blank=True, max_length=50, null=True, verbose_name='添加版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='Pythonfun.module', verbose_name='所属模块')),
                ('operation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pythonfun.operationtype', verbose_name='操作类型')),
            ],
            options={
                'verbose_name': '函数信息',
                'verbose_name_plural': '函数信息',
                'db_table': 'function_info',
                'unique_together': {('module', 'function_name')},
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='参数ID')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('parameter_name_cn', models.CharField(blank=True, max_length=100, null=True, verbose_name='参数中文名称')),
                ('data_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('default_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='默认值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('description_cn', models.TextField(blank=True, null=True, verbose_name='中文描述')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='Pythonfun.function', verbose_name='所属函数')),
            ],
            options={
                'verbose_name': '参数信息',
                'verbose_name_plural': '参数信息',
                'db_table': 'parameter_info',
                'unique_together': {('function', 'parameter_name')},
            },
        ),
    ]
