# Generated by Django 5.0 on 2025-08-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pythonfun', '0003_library_operationtype_module_function_parameter'),
    ]

    operations = [
    ]
