# Generated by Django 5.0.7

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Pythonfun', '0004_auto_20250815_1228'),
    ]

    operations = [
        # 文章表索引优化
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_type', 'is_published'], name='article_content_published_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='article_category_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='article_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'content_type', 'created_at'], name='article_published_content_created_idx'),
        ),
        
        # 子分类表索引优化
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['parent', 'is_enabled'], name='subcategory_parent_enabled_idx'),
        ),
        
        # 主分类表索引优化
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['is_enabled', 'order'], name='maincategory_enabled_order_idx'),
        ),
    ]
